name: Play DOOM in GitHub Actions
on: [workflow_dispatch]

jobs:
  doom:
    runs-on: ubuntu-latest
    steps:
      # 1. Instala o Chocolate Doom
      - name: Instalar Chocolate Doom
        run: |
          sudo apt-get update
          sudo apt-get install -y chocolate-doom

      # 2. Baixa o arquivo WAD (DOOM 1) de fonte alternativa
      - name: Baixar arquivo WAD (DOOM 1)
        run: |
          wget "https://www.doomworld.com/idgames/idstuff/doom/doom19a.zip" -O doom1.zip
          unzip doom1.zip "doom1.wad" -d .  # Extrai apenas o WAD
          if [ ! -f "doom1.wad" ]; then
            echo "❌ Erro: Arquivo WAD não encontrado após extração!"
            exit 1
          fi
          echo "✅ doom1.wad baixado com sucesso!"

      # 3. Executa o DOOM (modo terminal)
      - name: Rodar DOOM
        run: |
          echo "Use CTRL+C para sair."
          chocolate-doom -iwad doom1.wad -nosound
