name: Play TinyDoom in GitHub Actions
on: [workflow_dispatch]

jobs:
  doom:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libsdl2-dev

      # Usa HTTPS com token padrão do GitHub
      - name: Clonar TinyDoom (com autenticação)
        run: |
          git clone https://github.com/ozkl/tinydoom.git --depth 1

      - name: Compilar e executar TinyDoom
        run: |
          cd tinydoom
          make
          ./tinydoom
