name: Play TinyDoom in GitHub Actions
on: [workflow_dispatch]

jobs:
  doom:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar TinyDoom
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libsdl2-dev
          git clone https://github.com/ozkl/tinydoom.git
          cd tinydoom
          make

      - name: Rodar TinyDoom
        run: |
          ./tinydoom/tinydoom
